FROM node:14

# set working directory
WORKDIR /app
# copy project file
COPY package.json .
 
# install ALL node_modules, including 'devDependencies'
RUN npm install

# copy all project
COPY . .
 
CMD [ "npm", "test" ]

# Remove npmrc file because env variable NPM_TOKEN is set for travis projects
RUN rm -f ./.npmrc