version: "3.8"
services:
  vault-server:
    image: vault:latest
    command: sh ./data/configure-vault.sh
    volumes:
      - ./vault:/data
    ports:
      - "8201:8201"
    environment:
      VAULT_ADDR: "http://0.0.0.0:8201"
      VAULT_DEV_ROOT_TOKEN_ID: "vault-plaintext-root-token"
    cap_add:
      - IPC_LOCK